dist: xenial
language: python
python: 3.7
cache: pip
services: 
  - mysql
install:
  - mysql -e 'CREATE DATABASE memes;'
  - pip3 install -r requirements.txt

jobs:
  include:
    - stage: lint
      install:
        - pip3 install -r requirements-dev.txt
      script:
        - flake8 .
        - mypy .
    - stage: build
      script:
        - python3 Memologe_Test.py
