---
version: "3.2"

volumes:
  db:

networks:
  memologe:
  host:

services:
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - memologe
  #   restart: unless-stopped

  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - memologe
    environment:
      MYSQL_DATABASE: memes
      MYSQL_PASSWORD: memes_are_the_best
      MYSQL_USER: memologe
      MYSQL_ROOT_PASSWORD: test1
    restart: unless-stopped

  memologe:
    image: einspaten/memologe
    build: .
    depends_on:
      - db
    volumes:
      - /mnt/hdd/:/app/app/data/
    networks:
      - memologe
      - host
    environment:
      sqlite: 'False'
      # Mysql Stuff
      MYSQL_HOSTNAME: db
      MYSQL_USERNAME: memologe
      MYSQL_PASSWORD: memes_are_the_best
      MYSQL_PORT: 3306
      MYSQL_DATABASE: memes
      # Core Func.
      save_memes_to_disc: 'False'
      destination: /app/app/data/
      read_on_start: 'True'
      # Tokens required
      telegram_token: 
      discord_token:
      # Discord
      botname: Test # Required for Discord
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
