---
version: "3.2"

volumes:
  db:

networks:
  memologe:

services:
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - memologe
  #   restart: unless-stopped

  db:
    image: mariadb
    volumes:
      - $PWD/db:/var/lib/mysql
    networks:
      - memologe
    environment:
      MYSQL_DATABASE: memes
      MYSQL_PASSWORD: memes_are_the_best
      MYSQL_USER: memologe
      MYSQL_ROOT_PASSWORD: test1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
    restart: unless-stopped

  memologe:
    image: einspaten/memologe
    build: .
    depends_on:
      - db
    volumes:
      - $PWD/data/:/app/data/
      - $PWD/logs/:/app/logs/
    networks:
      - memologe
    environment:
      sqlite: 'False'
      MYSQL_HOSTNAME: db
      MYSQL_USERNAME: memologe
      MYSQL_PASSWORD: memes_are_the_best
      MYSQL_PORT: 3306
      MYSQL_DATABASE: memes
      save_memes_to_disc: 'False'
      destination: /app/data/
      config_log_destination: /app/logs/
      read_on_start: 'False'
      # at leat one token is required
      telegram_token:
      discord_token:
    restart: unless-stopped
