---
version: "3.2"
services:
  adminer:
    image: adminer    
    ports:
      - 8080:8080
    restart: unless-stopped

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_DATABASE: 'memes'
      MYSQL_PASSWORD: 'memes_are_the_best'
      MYSQL_ROOT_PASSWORD: memes_are_the_best      
      MYSQL_USER: 'memologe'      
   restart: unless-stopped
