---
version: "3.2"
services:
  adminer:
    image: adminer
    ports:
      - 8083:8080
    restart: unless-stopped
    networks:
      - memologe_net
  db:
    image: mysql #jsurf/rpi-mariadb
    environment:
      MYSQL_DATABASE: 'memes'
      MYSQL_PASSWORD: 'memes_are_the_best'
      MYSQL_USER: 'memologe'
      MYSQL_ROOT_PASSWORD: 'test1'
    ports:
      - 127.0.0.1:3306:3306
    restart: unless-stopped
    networks:
      - memologe_net
  memologe:
    image: memologe
    depends_on:
      - db
    restart: unless-stopped
    environment:
      debug: 'False'
      #Mysql Stuff
      MYSQL_HOSTNAME: 'db'
      MYSQL_USERNAME: 'memologe'
      MYSQL_PASSWORD: 'memes_are_the_best'
      MYSQL_PORT: 3306
      MYSQL_DATABASE: 'memes'
      # Core Func.
      save: 'True'
      destination: '/app/app/data/'
      read_on_start: 'False'
      #tokens
      tele_token: '778745612:AAHFnKvwmRTvS2wDtBlAvbCHXmHgjum9hYM' #Telegram Bot token
      disc_token: 'NTM2NjIxMzc2NjQ4MzgwNDQ1.DyetMw.blkw2eKf4LF_XlUmIgIf2Led470' #Discord Bot token
      #discord
      botname: 'Memologe#3481'

    volumes:
      - type: 'bind'
        source: '/mnt/hdd/'
        target: '/app/app/data/'
    networks:
      - memologe_net
      - host
networks:
  memologe_net:
  host:
