---
version: "3.2"
services:
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - memologe
  #   restart: unless-stopped

  db:
    image: mysql
    networks:
      - memologe
    environment:
      MYSQL_DATABASE: 'memes'
      MYSQL_PASSWORD: 'memes_are_the_best'
      MYSQL_USER: 'memologe'
      MYSQL_ROOT_PASSWORD: 'test1'
    restart: unless-stopped

  memologe:
    image: einspaten/memologe
    build: .
    depends_on:
      - db
    volumes:
      - /mnt/hdd/:/app/app/data/
    networks:
      - memologe
      - host
    environment:
      debug: 'False'
      # Mysql Stuff
      MYSQL_HOSTNAME: 'db'
      MYSQL_USERNAME: 'memologe'
      MYSQL_PASSWORD: 'memes_are_the_best'
      MYSQL_PORT: 3306
      MYSQL_DATABASE: 'memes'
      # Core Func.
      save: 'True'
      destination: '/app/app/data/'
      read_on_start: 'False'
      # Tokens required
      tele_token: ''
      disc_token: 'NTM2NjIxMzc2NjQ4MzgwNDQ1.XSCv7g.0sBfBZ0u1DqxeFOvcu8uEQaspE0'
      # Discord
      botname: 'Test' # Required for Discord
    restart: unless-stopped

networks:
  memologe:
  host:
